#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 1 2 3 4 5 6 7 8 9 
bspc monitor -d     

# bspc monitor -d          

bspc config border_width          2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


nitrogen --restore &
picom &
/home/adi/.config/polybar/launch.sh
sudo mount /dev/sda1 /hdd

# bspc config normal_border_color           "#ffffff00"
# bspc config active_border_color	          "#a7c080"
# bspc config focused_border_color	      "#a7c080"
# bspc config presel_feedback_color	      "#5e81ac"
# bspc config urgent_border_color 	      "#dd2727"

bspc config normal_border_color         "#00101010"
bspc config active_border_color         "#ffffff"
bspc config focused_border_color        "#ffffff"
bspc config presel_feedback_color       "#ffffff"
bspc config urgent_border_color         "#ffffff"


